### ISSUE TITLE
[bug/conflict] create all is only creating one item forcing you to click it multiple times.

### ISSUE THREAD

**Issue by JourneyOver** [Witnesscm/NDui_Plus#18]
Pretty much title. Not sure if it's something on NDui+ side or TradeSkillMaster side but upon having both enabled when you go into a profession to create an item and click on create all (on the default window and not TradeSkillMaster window) it will only make 1 item (even if you fill out the number to create all x amount of times) making you have to click the button again and again to continue crafting said item. 

Having NDui+ disabled but TradeSkillMaster enabled allows the create all function to work as intended; having TradeSkillMaster disabled but NDui+ enabled also allows the create all function to work as intended. 

If I have both enabled (both NDui+ and TradeSkillMaster) the only way that it ends up working as intended is if I enter the TradeSkillMaster window instead of the default profession window.

No errors or anything comes up, so I'm not really sure which one of the two addons is actually causing this issue in the end, so thought I'd come report it here (I plan on making a report to TradeSkillMaster as well when I can figure out how to exactly)

**Comment by Witnesscm** [comment]
This is a potential taint error, and I'm not sure how it's caused yet. You can try to disable Extended Vendor UI in console and test again.

**Comment by JourneyOver** [comment]
@Witnesscm hmm yea it seems to be something to do with the `Extended Vendor UI` that is causing it, upon disabling that it seems to work correctly.

**Comment by JourneyOver** [comment]
@Witnesscm so looking more into this because I started running into this issue again today even with `Extended Vendor UI` still disabled, I believe the addon that is actually causing this issue is Craftsim as disabling the Craftsim addon things started working again, even when I enable the `Extended Vendor UI` again..

Still going to do some more digging as time goes on because for now I'm not fully sure which of the three things is tainting things fully xD

**Comment by Witnesscm** [comment]
Thank you for the feedback. This is a tricky issue indeed. I also have this issue occasionally recently, but I didn't install Craftsim. So more than one addon can cause this issue. I'm looking for some steps to reproduce this issue stably.

**Comment by JourneyOver** [comment]
I'm going to go ahead and close this issue here, as I haven't ran into this issue in a very long time now. if it comes up again at any point in the future I'll re-open this issue.
