### ISSUE TITLE
[Feature Request] BetterBags

### ISSUE THREAD

**Issue by JourneyOver** [Witnesscm/NDui_Plus#29]
With AdiBags being deprecated, I was wondering if you have any plans to incorporate a skin for BetterBags, as it's supposed to be the replacement for AdiBags?

**Comment by Witnesscm** [comment]
Added in [10.2.2-alpha-3](https://github.com/Witnesscm/NDui_Plus/releases/tag/10.2.2-alpha-3).
If there are any missing skins, please reopen this issue.

**Comment by JourneyOver** [comment]
@Witnesscm Just to add a note on this even though there has already a theme for a while now and I thank you for it greatly, Cidan is working on an actual theme API for betterbags and he suggest anyone who is making themes for betterbags to move over to it once it's done. You can follow along with the theme API changes in this branch here -- https://github.com/Cidan/BetterBags/commits/better.tabs

**Comment by JourneyOver** [comment]
@Witnesscm 

One thing I've just noticed on at least one of my alts is that there are two quest icons on some items as shown in the following 
![Screenshot 2024-06-17 161137](https://github.com/Witnesscm/NDui_Plus/assets/13910285/1edb48de-de3a-41df-a832-8b0a1af46e79)

I have narrowed it down to NDUI+ betterbags skin being the cause of it as disabling the skin makes the icons only show the default betterbags ones. Unsure of why it's only those two items that are currently doing it as I haven't seen it happening on others (though I haven't been paying much attention until I seen it on an alt) but it'd be great to get this tiny detail looked into <3
