### ISSUE TITLE
[Misc:Extended Vendor] Sell all junk button is out of place if you interact with a merchant that doesn't have a repair options until you do.

### ISSUE THREAD

**Issue by JourneyOver** [Witnesscm/NDui_Plus#34]
**Description:**

This issue has been ongoing since the implementation of the "Sell All Junk" button in patch 10.1.5. While it hasn't caused major problems, it is persistent and should be addressed at some point.

**Problem:**

As shown in the image below, the "Sell All Junk" button is misaligned, overlapping with the page number on the right side.

![image](https://github.com/Witnesscm/NDui_Plus/assets/13910285/57e2aee0-6e11-4603-b7e9-b421d3c14b30)

**Steps to Reproduce:**

1. Log in to the game or use the `/reload` command.
2. Speak to a merchant that does not offer any repair options.
3. Observe the "Sell All Junk" button overlapping with the page number on the right side.

**Additional Information:**

- This issue appears only upon the first login or after using the `/reload` command.
- If you interact with a merchant that offers repair options, the buttons align correctly.
- Once the buttons align correctly with a merchant that offers repair options, they remain correct with other merchants, including those without repair options, until you log out or use `/reload` again.

**Expected Behavior:**

The "Sell All Junk" button should remain properly aligned regardless of the type of merchant interaction.

**Request:**

Please investigate and resolve this misalignment issue to improve the user interface consistency. Thank you.

**Comment by Witnesscm** [comment]
fixed in 11.0.0-alpha-5  👍
