### ISSUE TITLE
[Feature Request] Mount Journal & Krowi Achievement Filter skins

### ISSUE THREAD

**Issue by AngelosNaoumis** [Witnesscm/NDui_Plus#36]
Hello,

Is it possible to request skinning for the following addons?
Mount Journal
https://www.curseforge.com/wow/addons/mountsjournal
(sample skinning for ElvUI https://github.com/sfmict/MountsJournal-ElvUI-Skin)

Krowi Achievement Filter
https://www.curseforge.com/wow/addons/krowi-achievement-filter
(sample skinning for ElvUI https://github.com/TheKrowi/Krowi_AchievementFilter/blob/main/Plugins/ElvUI.lua)

**Comment by Witnesscm** [comment]
I'll take a look at the Mount Journal later this week.
As for the Krowi Achievement Filter, NDui (mainline) already includes its skin, see [Krowi_AF.lua](https://github.com/siweia/NDui/blob/master/Interface/AddOns/NDui/Modules/Skins/AddOns/Krowi_AF.lua)

**Comment by AngelosNaoumis** [comment]
Oh about Krowi Achievements i did not see any setting to active/deactivate so I though its not there.

Do you maybe know if I need to activate something or it just loads?

**Comment by Witnesscm** [comment]
just load Krowi Achievement Filter
![Screenshot](https://github.com/user-attachments/assets/20db5f87-c3ea-4f92-80c9-f95b1d67871d)

**Comment by AngelosNaoumis** [comment]
Using alpha build getting the below error. Removing the function on line 180 fixes the issue.


6x NDui_Plus: ...aceNDui_Plus/Modules/Skins/MountsJournal.lua:180: hooksecurefunc(): ADDON_LOADED is not a function
[string "=[C]"]: in function `hooksecurefunc'
[string "@NDui_Plus/Modules/Skins/MountsJournal.lua"]:180: in function <...aceNDui_Plus/Modules/Skins/MountsJournal.lua:171>
[string "=[C]"]: ?
[string "@NDui_Plus/Core/Core.lua"]:255: in function `CallLoadedAddon'
[string "@NDui_Plus/Core/Core.lua"]:325: in function `Initialize'
[string "@NDui_Plus/Core/Core.lua"]:340: in function `InitCallback'
[string "@NDui/Init.lua"]:144: in function `func'
[string "@NDui/Init.lua"]:23: in function <NDui/Init.lua:18>

Locals:

**Comment by Witnesscm** [comment]
fixed and finished in 11.0.3-alpha-3
