### ISSUE TITLE
[Feature Request] Request to skin Baganator

### ISSUE THREAD

**Issue by onedeadhero** [Witnesscm/NDui_Plus#38]
I feel bad doing this but I couldn't figure it out myself.  Would it be possible to request an ndUI-style skin for the addon [Baganator](https://www.curseforge.com/wow/addons/baganator)?  

I tried to figure it out myself by using [this skin](https://www.curseforge.com/wow/addons/baganator-simple-skin-dark) and using your BetterBags skin as a reference but I only ended up breaking the whole UI.

Thanks for taking time out of your day to read this request.

**Comment by AngelosNaoumis** [comment]
There is one ine works by owner of baganator.
Will be available in Curse soon, but you can download from github.
https://github.com/Baganator/Baganator-NDui

**Comment by onedeadhero** [comment]
> There is one ine works by owner of baganator. Will be available in Curse soon, but you can download from github. https://github.com/Baganator/Baganator-NDui

Wow, thank you so much for this.
