### ISSUE TITLE
[Bug] LS Toast skin error

### ISSUE THREAD

**Issue by AngelosNaoumis** [Witnesscm/NDui_Plus#39]
1x NDui_Plus: NDui_Plus/Modules/Skins/ls_Toasts.lua:88: attempt to index field 'options' (a nil value)
[string "@NDui_Plus/Modules/Skins/ls_Toasts.lua"]:88: in function <NDui_Plus/Modules/Skins/ls_Toasts.lua:81>
[string "=[C]"]: ?
[string "@NDui_Plus/Core/Core.lua"]:255: in function `CallLoadedAddon'
[string "@NDui_Plus/Core/Core.lua"]:325: in function `Initialize'
[string "@NDui_Plus/Core/Core.lua"]:340: in function `InitCallback'
[string "@NDui/Init.lua"]:144: in function `func'
[string "@NDui/Init.lua"]:23: in function <NDui/Init.lua:18>

Locals:
self = nil
LE = <table> {
 VER = <table> {
 }
 CHANGELOG = "- Fixed "[DNT] Worldsoul Memory Score" toasts.
"
}
LC = <table> {
 db = <table> {
 }
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field 'options' (a nil value)"
S = <table> {
 aceContainers = <table> {
 }
 db = <table> {
 }
 EarlyAceTooltips = <table> {
 }
 ToggleFrames = <table> {
 }
 EarlyAceWidgets = <table> {
 }
 name = "Skins"
 aceWidgets = <table> {
 }
 nonAddonsToLoad = <table> {
 }
}
_G = <table> {
 ERR_OUT_OF_CHI = "Not enough chi"
 DH_HAVOC_CORE_ABILITY_2 = "Strong melee attack that consumes Fury. If it critical strikes, some Fury is refunded."
 MultiCastActionButton6Cooldown = MultiCastActionButton6Cooldown {
 }
 MerchantItem9ItemButtonStock = MerchantItem9ItemButtonStock {
 }
 UNIT_NAMES_COMBATLOG_TOOLTIP = "Color unit names."
 HUD_EDIT_MODE_SETTING_ACTION_BAR_HIDE_BAR_ART = "Hide Bar Art"
 LE_GAME_ERR_CHAT_RAID_RESTRICTED_TRIAL = 783
 SPELL_FAILED_CUSTOM_ERROR_71 = "This partygoer wants to dance with you."
 LE_GAME_ERR_PET_SPELL_TARGETS_DEAD = 421
 ERROR_CLUB_TICKET_COUNT_AT_MAX_COMMUNITY = "Can't create any more invite links for this community."
 RecruitAFriendFrame = RecruitAFriendFrame {
 }
 SLASH_NDUI_AWCONFIG1 = "/ww"
 TutorialFrameLeft19 = TutorialFrameLeft19 {
 }
 MultiCastActionButton2Cooldown = MultiCastActionButton2Cooldown {
 }
 ERR_TRADE_EQUIPPED_BAG = "You can't trade equipped bags."
 PVP_RANK_6_1 = "Corporal"
 MultiBarLeftButton7 = MultiBarLeftButton7 {
 }
 OPTION_TOOLTIP_SHOW_MULTIBAR4 = "Attached to the left side of Right Action Bar 1 by default"
 LE_GAME_ERR_INVALID_FOLLOW_PVP_COMBAT = 375
 MerchantItem3AltCurrencyFrameItem1Text = MerchantItem3AltCurrencyFrameItem1Text {
 }
 PROFESSIONS_COLUMN_REAGENTS_NONE = "None"
 OPTION_SHOW_ACTION_BAR5_TOOLTIP = "Attached to the left side of Action Bar 4 by default"
 BINDING_NAME_NAMEPLATES = "Show Enemy Nameplates"
 INSTANCE_UNAVAILABLE_OTHER_TEMPORARILY_DISABLED = "%s cannot enter. This instance is temporarily disabled."
 COVENANT_MISSIONS_HEALTH = "Health"
 MAIL_LETTER_TOOLTIP = "Click to make a permanent
copy of this letter."
 PVPReadyDialogBottomArt = PVPReadyDialogBottomArt {
 }
 MultiBar6Button4Flash = MultiBar6Button4Flash {
 }
 ERR_NOAMMO_S = "%s"
 CHAT_CONFIG_OTHER_COMBAT = <table> {
 }
 RematchGameTooltipTexture13 = RematchGameTooltipTexture13 {
 }
 ClassNameplateBarPaladinFrameRune5 = ClassNameplateBarPaladinFrameRune5 {
 }
 TutorialFrameRight19 = TutorialFrameRight19 {
 }
 BOOST2_WARRIOR_COLOSSUSSMASH = "Use |cFFFFFFFFColossus Smash|r.

|cFFFFFFFFColossus Smash|r increases your damage."
 BN_UNABLE_TO_RESOLVE_NAME = "Unable to whisper '%s'. Blizzard services may be unavailable."
 CinematicFrameRaidBossEmoteFrame = CinematicFrameRaidBossEmoteFrame {
 }
 LE_GAME_ERR_ONLY_ONE_QUIVER = 36
 INT_SPELL_DURATION_HOURS = "%d |4hour:hrs;"
 SLASH_LibQTip1 = "/qtip"
 LOSS_OF_CONTROL_DISPLAY_FEAR = "Feared"
 POWERBAR_PREDICTION_COLOR_MAELSTROM_CODE = "|cff003366"
 AUCTIONATOR_L_CONFIG_ALTERNATE_SCAN = "Use alternate slower scan mode by default"
 BankFrameItem17SearchOverlay = BankFrameItem17SearchOverlay {
 }
 AUCTIONATOR_L_DEFAULT_LIST_HEADER = "Default Shopping List"
 DMG_LCD = "DMG"
 ACTION_SPELL_MISSED_POSSESSIVE = "1"
 SLASH_STOPATTACK1 = "/stopattack"
 MAP_LEGEND_RARE_TOOLTIP = "A special creature that provides various rewards"
 MultiCastActionButton4HotKey = MultiCastActionButton4HotKey {
 }
 MINIMAP_TRACKING_TRAINER_CLASS = "Class Trainer"
 SLASH_DISMOUNT2 = "/dismount"
 DUNGEON_FLOOR_DRAGONBLIGHTCHROMIESCENARIO2 = "Andorhal"
 EMOTE69_CMD1 = "/nosepick"
 WowTokenRedemptionFrameBg = WowTokenRedemptionFrameBg {
 }
 ITEM_REQ_PURCHASE_GUILD_LEVEL = "Requires guild level %d"
 AutoFollowStatus = AutoFollowStatus {
 }
 ARENA_CASUAL = "Skirmish"
 STABLE_PET_ABILITIES_LIST_HEADER = "Special Abilities"
 SendStationeryBackgroundRight = SendStationeryBackgroundRight {
 }
 MultiBarLeftButton11Name = MultiBarLeftButton11Name {
 }
 KEY_ABBR_PADLSTICK = "|A:Gamepad_Gen_LStickIn_32:14:14|a"
 CONQUEST_BAR = "Conquest %d / %d"
 MultiBarLeft

**Comment by Witnesscm** [comment]
fixed in 11.0.2
