### ISSUE TITLE
[Issue[ New issue with patch 11.0.2

### ISSUE THREAD

**Issue by AngelosNaoumis** [Witnesscm/NDui_Plus#42]
Getting below error.

1x NDui_Plus: ...aceNDui_Plus/Modules/Skins/MountsJournal.lua:198: attempt to index local 'self' (a nil value)
[string "@NDui_Plus/Modules/Skins/MountsJournal.lua"]:198: in function <...aceNDui_Plus/Modules/Skins/MountsJournal.lua:184>
[string "=[C]"]: ?
[string "@NDui_Plus/Core/Core.lua"]:255: in function `CallLoadedAddon'
[string "@NDui_Plus/Core/Core.lua"]:325: in function `Initialize'
[string "@NDui_Plus/Core/Core.lua"]:340: in function `InitCallback'
[string "@NDui/Init.lua"]:144: in function `func'
[string "@NDui/Init.lua"]:23: in function <NDui/Init.lua:18>

Locals:
self = nil
MountsJournal = MountsJournal {
 swimmingVashjir = <table> {
 }
 herbMount = false
 magicBrooms = <table> {
 }
 cameraConfig = <table> {
 }
 filters = <table> {
 }
 charDB = <table> {
 }
 mapVashjir = <table> {
 }
 defMountsListID = 946
 empty = <table> {
 }
 list = <table> {
 }
 priorityProfiles = <table> {
 }
 sFlags = <table> {
 }
 defProfile = <table> {
 }
 herbalismMounts = <table> {
 }
 additionalFavorites = <table> {
 }
 usableRepairMounts = <table> {
 }
 globalDB = <table> {
 }
 config = <table> {
 }
 help = <table> {
 }
 lowLevel = <table> {
 }
 defFilters = <table> {
 }
 summonPanel = Frame {
 }
 usableIDs = <table> {
 }
 profiles = <table> {
 }
}
MountsJournalFrame = MountsJournalFrame {
 MountJournal = MountJournal {
 }
 tags = <table> {
 }
 indexByMountID = <table> {
 }
 mountTypes = <table> {
 }
 CollectionsJournal = CollectionsJournal {
 }
 filters = <table> {
 }
 useMountsJournalButton = CheckButton {
 }
 frameState = <table> {
 }
 mjFiltersBackup = <table> {
 }
 colors = <table> {
 }
}
(*temporary) = <table> {
 aceContainers = <table> {
 }
 db = <table> {
 }
 EarlyAceTooltips = <table> {
 }
 ToggleFrames = <table> {
 }
 EarlyAceWidgets = <table> {
 }
 name = "Skins"
 aceWidgets = <table> {
 }
 nonAddonsToLoad = <table> {
 }
}
(*temporary) = "ReskinCheck"
(*temporary) = MJTooltipModel {
 NineSlice = Frame {
 }
 layoutType = "TooltipDefaultLayout"
 model = PlayerModel {
 }
 tipStyled = true
 bg = Frame {
 }
}
(*temporary) = 1.001565
(*temporary) = 1.001565
(*temporary) = nil
(*temporary) = Frame {
 __bgTex = Texture {
 }
 PixelSnapDisabled = true
 __shadow = Frame {
 }
 Center = Texture {
 }
 RightEdge = Texture {
 }
 backdropInfo = <table> {
 }
 BottomEdge = Texture {
 }
 BottomLeftCorner = Texture {
 }
 BottomRightCorner = Texture {
 }
 TopEdge = Texture {
 }
 TopRightCorner = Texture {
 }
 TopLeftCorner = Texture {
 }
 LeftEdge = Texture {
 }
}
(*temporary) = "attempt to index local 'self' (a nil value)"
C = <table> {
 ClickCastList = <table> {
 }
 CustomUnits = <table> {
 }
 BadBoys = <table> {
 }
 Minimap = <table> {
 }
 DeprecatedAuras = <table> {
 }
 Skins = <table> {
 }
 TrashUnits = <table> {
 }
 UFs = <table> {
 }
 CornerBuffs = <table> {
 }
 TalentCDFix = <table> {
 }
 Infobar = <table> {
 }
 PartySpells = <table> {
 }
 RaidBuffsWhite = <table> {
 }
 frames = <table> {
 }
 Auras = <table> {
 }
 BlackList = <table> {
 }
 mult = 1.001565
 db = <table> {
 }
 margin = 3
 IgnoreQuestNPC = <table> {
 }
 MajorSpells = <table> {
 }
 AuraWatchList = <table> {
 }
 otherSkins = <table> {
 }
 Tooltips = <table> {
 }
 PartySpellsDB = <table> {
 }
 RaidDebuffs = <table> {
 }
 themes = <table> {
 }
 RaidDebuffsBlack = <table> {
 }
 defaultThemes = <table> {
 }
 ShowTargetNPCs = <table> {
 }
 WhiteList = <table> {
 }
 PowerUnits = <table> {
 }
 Bars = <table> {
 }
}
P = <table> {
 CharacterSettings = <table> {
 }
 InfoColors = <table> {
 }
 TextureTable = <table> {
 }
 RotationRightTex = "Interface\Addons\NDui_Plus\Media\Texture\UI-RotationRight-Big-Up"
 Blank = "Interface\Addons\NDui_Plus\Media\Texture\Blank"
 RoleList = <table> {
 }
 ArrowDown = "Interface\Addons\NDui_Plus\Media\Texture\arrow-down"
 ArrowUp = "Interface\Addons\NDui_Plus\Media\Texture\arrow-up"
 WaitFrame = NDuiPlus_WaitFrame {
 }
 WaitTable = <table> {
 }
 Version = "@project-version@"
 SupportVersion = "8.0.0"
 isNewPatch = true
 AnimShake = <table> {
 }
 EasyMenu = NDuiPlus_EasyMenu {
 }
 Changelog = "v11.0.2
[|cffFF1414主要|r] 需要NDui v8.0.0 以上版本
[美化] 更新 WeakAuras 美化提醒
[美化] 更新部分插件美化
[易用性] 修复巅峰声望奖励
[易用性] 修复随从报告面板标签

v11.0.1
[主要] 适配11.0.2 API改动
[美化] 添加 WeakAuras 美化提醒
[美化] 添加 ShadowDancer 美化
[美化] 调整 Immersion 按钮美化
[鼠标提示] 修复PvE进度未正常对满级角色生效的问题
[单位框体] 更新 oUF_Fader

v11.0.0
[主要] 更新版本号至11.0.0; 适配部分API改动
[易用性] 调整启用商人面板扩展时售卖垃圾按钮位置
[易用性] 移除兽栏面板扩

**Comment by AngelosNaoumis** [comment]
Last git versions always.

Its mostly due to 11.0.2 changes

**Comment by Witnesscm** [comment]
ok, should be fixed in 11.0.3-alpha-4
