### ISSUE TITLE
听说ndp提供了修改wa边框的功能

### ISSUE THREAD

**Issue by tyrival** [Witnesscm/NDui_Plus#43]
wa在某个版本后禁止了ndui修改边框素材，之前一直是通过修改
World of Warcraft Classic\_classic_\Interface\AddOns\WeakAuras\RegionTypes\RegionPrototype.lua
在13行增加
WeakAuras.regionPrototype = Private.regionPrototype

刚听说ndp提供了修改方案，不用改wa源码了，请问下应该怎么做

**Comment by Witnesscm** [comment]
https://github.com/Witnesscm/NDui_Plus/wiki/WeakAuras2%E2%80%90%E7%9A%AE%E8%82%A4%E2%80%90%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98
