### ISSUE TITLE
BetterBags error

### ISSUE THREAD

**Issue by Straitypicks** [Witnesscm/NDui_Plus#45]
Message: ...erface/AddOns/NDui_Plus/Modules/Skins/BetterBags.lua:181: attempt to call method 'EnumerateActive' (a nil value)
Time: Thu Sep 19 06:16:30 2024
Count: 3
Stack: ...erface/AddOns/NDui_Plus/Modules/Skins/BetterBags.lua:181: attempt to call method 'EnumerateActive' (a nil value)
[string "@Interface/AddOns/NDui_Plus/Modules/Skins/BetterBags.lua"]:181: in function `func'
[string "@Interface/AddOns/NDui/Init.lua"]:23: in function <Interface/AddOns/NDui/Init.lua:18>

Locals: (*temporary) = nil
(*temporary) = <table> {
 items = <table> {
 }
}
(*temporary) = "attempt to call method 'EnumerateActive' (a nil value)"
ItemFrame = <table> {
 emptyItemTooltip = BetterBagsEmptySlotTooltip {
 }
 _pool = <table> {
 }
 baseName = "BetterBags"
 modules = <table> {
 }
 defaultModuleLibraries = <table> {
 }
 enabledState = true
 itemProto = <table> {
 }
 moduleName = "ItemFrame"
 defaultModuleState = true
 name = "BetterBags_ItemFrame"
 orderedModules = <table> {
 }
}
Themes = <table> {
 modules = <table> {
 }
 defaultModuleLibraries = <table> {
 }
 name = "BetterBags_Themes"
 orderedModules = <table> {
 }
 itemButtons = <table> {
 }
 defaultModuleState = true
 windows = <table> {
 }
 baseName = "BetterBags"
 themes = <table> {
 }
 enabledState = true
 titles = <table> {
 }
 tabs = <table> {
 }
 moduleName = "Themes"
 sectionFonts = <table> {
 }
}

**Comment by Witnesscm** [comment]
fixed in 11.0.6-alpha-1
